name: PR Tests

on:
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout PR Branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
        
    - name: Install dependencies and run tests
      run: |
        uv sync --extra test
        uv run pytest
